apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: my-pvc

      initContainers:
        - name: init-write
          image: busybox
          command: ["sh", "-c", "echo 'Hello from PVC!' > /data/message.txt"]
          volumeMounts:
            - name: app-storage
              mountPath: /data

      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
